### ISSUE TITLE
general error

### ISSUE THREAD

**Issue by agreements** [Wardormeur/phpbbwpunicorn#1]
Warning: require_once(/var/www/wp/wp-content/plugins/wpphpbbunicorn-master/lib/ClassLoader/UniversalClassLoader.php): failed to open stream: No such file or directory in /var/www/wp/wp-content/plugins/wpphpbbunicorn-master/wpphpbbunicorn.php on line 14

Seems to be a bug :)

**Comment by Wardormeur** [comment]
You're on the wrong repo, but yeah, i havent been pushing for a while. Sorry about that, gonna fix asap
