### ISSUE TITLE
Does not enable 

### ISSUE THREAD

**Issue by knockbeats** [Wardormeur/phpbbwpunicorn#2]
Hello, I really like what you are trying to do with your extension/plugin, would really like to use them, it would be the perfect solution for something I've been wanting to implement,  however I get issues with both this extension, and the wp plugin.  

For this extension: When I go to enable it in "Manage Extensions", the screen just goes white.  I have to go back to forum index, and then re-enter the admin control panel to get back in (simply refreshing the acp page will not reload from the white page).  When I get back to Manage Extensions, the extension shows the action "Enable" still.  I can never get it to actually enable.  

As for the WP plugin: I can get it to activate, however when I set my path (mine is located at /forums/ rather than /phpbb3/) in the settings to "/PathFromServer/forums/config.php" (yours defaults to "/PathFromServer/phpbb3/config.php"), then hit save, the page sits there doing nothing, and then if I reload /wp-admin/, or try to hit the main WP URL, it gets a white page.  The only remedy to this is to either remove the plugin files from the server, or go into the database and remove the wpphpbb created entries.  

my paths are (not exactly, but similar to this):
home/name/public_html/WP/forums/ext/wardormeur/phpbbwpunicorn/
home/name/public_html/WP/wp-content/plugins/wpphpbbunicorn/

Any help is greatly appreciated!

Thank you so much, I hope to be using your amazing plugin soon!

**Comment by Wardormeur** [comment]
About phpbbtowp : i may be missing a check to ensure it doesnt lock in case of wrong path, i'll look at it.
At activation, the plugin look for a Wordpress install to a 3 level further from phpbb. I'm surprised it didnt find yours, regarding your configuration. 
Path must be relative (i know it's strange) to the admin page. Consider phpbb and wp having their folder at the same level (/wordpress & /phpbb), the path for phpbb will be ../../wordpress. The reason behind it is that Phpbb use symfony container through a naming using the phpbb_root_path, which doesnt interpret the ":" of a Windows disk, rendering the plugin unusable for Windows folks. I may ask for a fix on their side.
About wptophpbb : same thing, path must be relative, but to the root folder of wordpress, rendering a ../phpbb in my scenario.
In yours, you may try for phpbb : ../../../WP ; and for WP : forums/
That makes me think i have to fix this trailing shalsh thingy.
BTW: regarding the white screen on WP, i just fixed it, it's the exact same scenario of missing some check on the validity of the path.

**Comment by knockbeats** [comment]
Thank you for your quick reply, i look forward to the next update of the phpbb extension.  

I will move my wp plugin questions over to the proper page :)
