### ISSUE TITLE
Ext panel crash after wrong path

### ISSUE THREAD

**Issue by RARgames** [Wardormeur/phpbbwpunicorn#4]
Just one more issue I have found :d
When I write wrong path in "wp path" The ext panel crashed with error:

[phpBB Debug] PHP Warning: in file [ROOT]/ext/wardormeur/phpbbwpunicorn/acp/phpbbwpunicorn_module.php on line 38: require_once(..//wp-load.php): failed to open stream: No such file or directory
Fatal error: require_once(): Failed opening required '..//wp-load.php' (include_path='.:/usr/local/php/pear5') in /forum/ext/wardormeur/phpbbwpunicorn/acp/phpbbwpunicorn_module.php on line 38

Solution: disable ext, delete data, enable ext

**Comment by RARgames** [comment]
I think I have correct path now but half of the settings are missing after I save path in ext panel. They are saved(just non changeable)? or it is a bug?

**Comment by RARgames** [comment]
After creating a new user I have this error:(in phpbb)(It creates user in wp but I can't log into this test user.EDIT: any user
[phpBB Debug] PHP Warning: in file [ROOT]/ext/wardormeur/phpbbwpunicorn/user.php on line 103: Invalid argument supplied for foreach()
[phpBB Debug] PHP Warning: in file [ROOT]/ext/wardormeur/phpbbwpunicorn/user.php on line 103: Invalid argument supplied for foreach()
[phpBB Debug] PHP Warning: in file [ROOT]/ext/wardormeur/phpbbwpunicorn/user.php on line 103: Invalid argument supplied for foreach()
[phpBB Debug] PHP Warning: in file [ROOT]/ext/wardormeur/phpbbwpunicorn/user.php on line 103: Invalid argument supplied for foreach()
[phpBB Debug] PHP Warning: in file [ROOT]/ext/wardormeur/phpbbwpunicorn/user.php on line 103: Invalid argument supplied for foreach()
[phpBB Debug] PHP Warning: in file [ROOT]/ext/wardormeur/phpbbwpunicorn/user.php on line 103: Invalid argument supplied for foreach()

Warning: Cannot modify header information - headers already sent by (output started at /forum/includes/functions.php:3899) in /forum/includes/functions.php on line 5235

Warning: Cannot modify header information - headers already sent by (output started at /forum/includes/functions.php:3899) in /forum/includes/functions.php on line 5235

Warning: Cannot modify header information - headers already sent by (output started at /forum/includes/functions.php:3899) in /forum/includes/functions.php on line 5235

**Comment by Wardormeur** [comment]
I'll look into this asap, thakns for the feedback
I think that the 2nd error comes from the fact the roles for the mapping are not defined, should make a check over using it/n

**Comment by RARgames** [comment]
I'm checking the latest version of this 2(pl and ext) but I can't get it working. Do I have to set some special options in wordpress or phpbb to get it working?

**Comment by Wardormeur** [comment]
I'm still on it

**Comment by Wardormeur** [comment]
Updated :)

**Comment by RARgames** [comment]
not working(session and user sync) it creates user in wp but password not working, email not set in wp(also something strange happens, it changed my admin password and I had to recover it by email)

after new register:
[phpBB Debug] PHP Warning: in file [ROOT]/ext/wardormeur/phpbbwpunicorn/user.php on line 103: Invalid argument supplied for foreach()
[phpBB Debug] PHP Warning: in file [ROOT]/ext/wardormeur/phpbbwpunicorn/user.php on line 103: Invalid argument supplied for foreach()
[phpBB Debug] PHP Warning: in file [ROOT]/ext/wardormeur/phpbbwpunicorn/user.php on line 103: Invalid argument supplied for foreach()
[phpBB Debug] PHP Warning: in file [ROOT]/ext/wardormeur/phpbbwpunicorn/user.php on line 103: Invalid argument supplied for foreach()
[phpBB Debug] PHP Warning: in file [ROOT]/ext/wardormeur/phpbbwpunicorn/user.php on line 103: Invalid argument supplied for foreach()
[phpBB Debug] PHP Warning: in file [ROOT]/ext/wardormeur/phpbbwpunicorn/user.php on line 103: Invalid argument supplied for foreach()

Warning: Cannot modify header information - headers already sent by (output started at /forum/includes/functions.php:3899) in /forum/includes/functions.php on line 5235

Warning: Cannot modify header information - headers already sent by (output started at /forum/includes/functions.php:3899) in /forum/includes/functions.php on line 5235

Warning: Cannot modify header information - headers already sent by (output started at /forum/includes/functions.php:3899) in /forum/includes/functions.php on line 5235

**Comment by Wardormeur** [comment]
Ok, i just had it, Ididn't know you had specified some association between roles :)
BRB with the solution

**Comment by Wardormeur** [comment]
Thanks to @Elsensee for his help, this should be fixed. Sorry for misunderstanding this error :/
