### ISSUE TITLE
Default role

### ISSUE THREAD

**Issue by RARgames** [Wardormeur/phpbbwpunicorn#5]
I set default role:"subscriber" in phpbbwp ext, wp is giving role author to every new user

**Comment by Wardormeur** [comment]
The default role is overwritten by the role association. Do you have any that is set for this group ?

**Comment by RARgames** [comment]
![roles](https://cloud.githubusercontent.com/assets/13639766/9154899/984509cc-3ea4-11e5-9656-de9e3b1dcdbf.png)

**Comment by RARgames** [comment]
And I want default wp role: sub
wp Autors = registered

When I make changes in wp users, does it affect phpbb user or it's only one way?

**Comment by Wardormeur** [comment]
It's only one way.
You can't set registred users as both author and subscriber, as WP handle only one role per user, so that the "higher" defined (author here) for the same phpbb group is the one choosed over creation or Resynchronization.

**Comment by RARgames** [comment]
so the solution is to create group authors in phpbb and give them the same perms as registered?

**Comment by Wardormeur** [comment]
Well, if you want some of your users but not everyone to be an author, you need to separate them from the rest of the registred users, yes.

**Comment by RARgames** [comment]
thanks for help
