### ISSUE TITLE
error after regenerate temporary files

### ISSUE THREAD

**Issue by RARgames** [Wardormeur/phpbbwpunicorn#6]
When You reload the site it seems to work correctly

but here you can see everything :P 
 [phpBB Debug] PHP Notice: in file [ROOT]/ext/wardormeur/phpbbwpunicorn/user.php on line 33: Constant SHORTINIT already defined
[phpBB Debug] PHP Notice: in file [ROOT]/ext/wardormeur/phpbbwpunicorn/user.php on line 131: Undefined index: user_website
[phpBB Debug] PHP Notice: in file [ROOT]/ext/wardormeur/phpbbwpunicorn/user.php on line 135: Undefined index: user_aim
[phpBB Debug] PHP Notice: in file [ROOT]/ext/wardormeur/phpbbwpunicorn/user.php on line 136: Undefined index: user_yim
[phpBB Debug] PHP Notice: in file /wp-includes/pluggable.php on line 801: Use of undefined constant AUTH_COOKIE - assumed 'AUTH_COOKIE'
[phpBB Debug] PHP Notice: in file [ROOT]/ext/wardormeur/phpbbwpunicorn/user.php on line 131: Undefined index: user_website
[phpBB Debug] PHP Notice: in file [ROOT]/ext/wardormeur/phpbbwpunicorn/user.php on line 135: Undefined index: user_aim
[phpBB Debug] PHP Notice: in file [ROOT]/ext/wardormeur/phpbbwpunicorn/user.php on line 136: Undefined index: user_yim
[phpBB Debug] PHP Notice: in file [ROOT]/ext/wardormeur/phpbbwpunicorn/user.php on line 131: Undefined index: user_website
[phpBB Debug] PHP Notice: in file [ROOT]/ext/wardormeur/phpbbwpunicorn/user.php on line 135: Undefined index: user_aim
[phpBB Debug] PHP Notice: in file [ROOT]/ext/wardormeur/phpbbwpunicorn/user.php on line 136: Undefined index: user_yim
[phpBB Debug] PHP Notice: in file [ROOT]/ext/wardormeur/phpbbwpunicorn/user.php on line 131: Undefined index: user_website
[phpBB Debug] PHP Notice: in file [ROOT]/ext/wardormeur/phpbbwpunicorn/user.php on line 135: Undefined index: user_aim
[phpBB Debug] PHP Notice: in file [ROOT]/ext/wardormeur/phpbbwpunicorn/user.php on line 136: Undefined index: user_yim
[phpBB Debug] PHP Notice: in file [ROOT]/ext/wardormeur/phpbbwpunicorn/user.php on line 131: Undefined index: user_website
[phpBB Debug] PHP Notice: in file [ROOT]/ext/wardormeur/phpbbwpunicorn/user.php on line 135: Undefined index: user_aim
[phpBB Debug] PHP Notice: in file [ROOT]/ext/wardormeur/phpbbwpunicorn/user.php on line 136: Undefined index: user_yim
[phpBB Debug] PHP Notice: in file [ROOT]/ext/wardormeur/phpbbwpunicorn/user.php on line 131: Undefined index: user_website
[phpBB Debug] PHP Notice: in file [ROOT]/ext/wardormeur/phpbbwpunicorn/user.php on line 135: Undefined index: user_aim
[phpBB Debug] PHP Notice: in file [ROOT]/ext/wardormeur/phpbbwpunicorn/user.php on line 136: Undefined index: user_yim
[phpBB Debug] PHP Notice: in file [ROOT]/ext/wardormeur/phpbbwpunicorn/user.php on line 131: Undefined index: user_website
[phpBB Debug] PHP Notice: in file [ROOT]/ext/wardormeur/phpbbwpunicorn/user.php on line 135: Undefined index: user_aim
[phpBB Debug] PHP Notice: in file [ROOT]/ext/wardormeur/phpbbwpunicorn/user.php on line 136: Undefined index: user_yim
[phpBB Debug] PHP Notice: in file [ROOT]/ext/wardormeur/phpbbwpunicorn/user.php on line 131: Undefined index: user_website
[phpBB Debug] PHP Notice: in file [ROOT]/ext/wardormeur/phpbbwpunicorn/user.php on line 135: Undefined index: user_aim
[phpBB Debug] PHP Notice: in file [ROOT]/ext/wardormeur/phpbbwpunicorn/user.php on line 136: Undefined index: user_yim
[phpBB Debug] PHP Notice: in file [ROOT]/ext/wardormeur/phpbbwpunicorn/user.php on line 131: Undefined index: user_website
[phpBB Debug] PHP Notice: in file [ROOT]/ext/wardormeur/phpbbwpunicorn/user.php on line 135: Undefined index: user_aim
[phpBB Debug] PHP Notice: in file [ROOT]/ext/wardormeur/phpbbwpunicorn/user.php on line 136: Undefined index: user_yim
[phpBB Debug] PHP Notice: in file [ROOT]/ext/wardormeur/phpbbwpunicorn/user.php on line 131: Undefined index: user_website
[phpBB Debug] PHP Notice: in file [ROOT]/ext/wardormeur/phpbbwpunicorn/user.php on line 135: Undefined index: user_aim
[phpBB Debug] PHP Notice: in file [ROOT]/ext/wardormeur/phpbbwpunicorn/user.php on line 136: Undefined index: user_yim
[phpBB Debug] PHP Notice: in file [ROOT]/ext/wardormeur/phpbbwpunicorn/user.php on line 131: Undefined index: user_website
[phpBB Debug] PHP Notice: in file [ROOT]/ext/wardormeur/phpbbwpunicorn/user.php on line 135: Undefined index: user_aim
[phpBB Debug] PHP Notice: in file [ROOT]/ext/wardormeur/phpbbwpunicorn/user.php on line 136: Undefined index: user_yim
[phpBB Debug] PHP Notice: in file [ROOT]/ext/wardormeur/phpbbwpunicorn/user.php on line 131: Undefined index: user_website
[phpBB Debug] PHP Notice: in file [ROOT]/ext/wardormeur/phpbbwpunicorn/user.php on line 135: Undefined index: user_aim
[phpBB Debug] PHP Notice: in file [ROOT]/ext/wardormeur/phpbbwpunicorn/user.php on line 136: Undefined index: user_yim
[phpBB Debug] PHP Notice: in file [ROOT]/ext/wardormeur/phpbbwpunicorn/user.php on line 131: Undefined index: user_website
[phpBB Debug] PHP Notice: in file [ROOT]/ext/wardormeur/phpbbwpunicorn/user.php on line 135: Undefined index: user_aim
[phpBB Debug] PHP Notice: in file [ROOT]/ext/wardormeur/phpbbwpunicorn/user.php on line 136: Undefined index: user_yim
[phpBB Debug] PHP Notice: in file [ROOT]/ext/wardormeur/phpbbwpunicorn/user.php on line 131: Undefined index: user_website
[phpBB Debug] PHP Notice: in file [ROOT]/ext/wardormeur/phpbbwpunicorn/user.php on line 135: Undefined index: user_aim
[phpBB Debug] PHP Notice: in file [ROOT]/ext/wardormeur/phpbbwpunicorn/user.php on line 136: Undefined index: user_yim
[phpBB Debug] PHP Notice: in file [ROOT]/ext/wardormeur/phpbbwpunicorn/user.php on line 131: Undefined index: user_website
[phpBB Debug] PHP Notice: in file [ROOT]/ext/wardormeur/phpbbwpunicorn/user.php on line 135: Undefined index: user_aim
[phpBB Debug] PHP Notice: in file [ROOT]/ext/wardormeur/phpbbwpunicorn/user.php on line 136: Undefined index: user_yim
[phpBB Debug] PHP Notice: in file [ROOT]/ext/wardormeur/phpbbwpunicorn/user.php on line 131: Undefined index: user_website
[phpBB Debug] PHP Notice: in file [ROOT]/ext/wardormeur/phpbbwpunicorn/user.php on line 135: Undefined index: user_aim
[phpBB Debug] PHP Notice: in file [ROOT]/ext/wardormeur/phpbbwpunicorn/user.php on line 136: Undefined index: user_yim
[phpBB Debug] PHP Notice: in file [ROOT]/ext/wardormeur/phpbbwpunicorn/user.php on line 131: Undefined index: user_website
[phpBB Debug] PHP Notice: in file [ROOT]/ext/wardormeur/phpbbwpunicorn/user.php on line 135: Undefined index: user_aim
[phpBB Debug] PHP Notice: in file [ROOT]/ext/wardormeur/phpbbwpunicorn/user.php on line 136: Undefined index: user_yim
[phpBB Debug] PHP Notice: in file [ROOT]/ext/wardormeur/phpbbwpunicorn/user.php on line 131: Undefined index: user_website
[phpBB Debug] PHP Notice: in file [ROOT]/ext/wardormeur/phpbbwpunicorn/user.php on line 135: Undefined index: user_aim
[phpBB Debug] PHP Notice: in file [ROOT]/ext/wardormeur/phpbbwpunicorn/user.php on line 136: Undefined index: user_yim
[phpBB Debug] PHP Notice: in file [ROOT]/ext/wardormeur/phpbbwpunicorn/user.php on line 131: Undefined index: user_website
[phpBB Debug] PHP Notice: in file [ROOT]/ext/wardormeur/phpbbwpunicorn/user.php on line 135: Undefined index: user_aim
[phpBB Debug] PHP Notice: in file [ROOT]/ext/wardormeur/phpbbwpunicorn/user.php on line 136: Undefined index: user_yim
[phpBB Debug] PHP Notice: in file [ROOT]/ext/wardormeur/phpbbwpunicorn/user.php on line 131: Undefined index: user_website
[phpBB Debug] PHP Notice: in file [ROOT]/ext/wardormeur/phpbbwpunicorn/user.php on line 135: Undefined index: user_aim
[phpBB Debug] PHP Notice: in file [ROOT]/ext/wardormeur/phpbbwpunicorn/user.php on line 136: Undefined index: user_yim
[phpBB Debug] PHP Notice: in file [ROOT]/ext/wardormeur/phpbbwpunicorn/user.php on line 131: Undefined index: user_website
[phpBB Debug] PHP Notice: in file [ROOT]/ext/wardormeur/phpbbwpunicorn/user.php on line 135: Undefined index: user_aim
[phpBB Debug] PHP Notice: in file [ROOT]/ext/wardormeur/phpbbwpunicorn/user.php on line 136: Undefined index: user_yim
[phpBB Debug] PHP Notice: in file [ROOT]/ext/wardormeur/phpbbwpunicorn/user.php on line 131: Undefined index: user_website
[phpBB Debug] PHP Notice: in file [ROOT]/ext/wardormeur/phpbbwpunicorn/user.php on line 135: Undefined index: user_aim
[phpBB Debug] PHP Notice: in file [ROOT]/ext/wardormeur/phpbbwpunicorn/user.php on line 136: Undefined index: user_yim
[phpBB Debug] PHP Notice: in file [ROOT]/ext/wardormeur/phpbbwpunicorn/user.php on line 131: Undefined index: user_website
[phpBB Debug] PHP Notice: in file [ROOT]/ext/wardormeur/phpbbwpunicorn/user.php on line 135: Undefined index: user_aim
[phpBB Debug] PHP Notice: in file [ROOT]/ext/wardormeur/phpbbwpunicorn/user.php on line 136: Undefined index: user_yim
[phpBB Debug] PHP Notice: in file [ROOT]/ext/wardormeur/phpbbwpunicorn/user.php on line 131: Undefined index: user_website
[phpBB Debug] PHP Notice: in file [ROOT]/ext/wardormeur/phpbbwpunicorn/user.php on line 135: Undefined index: user_aim
[phpBB Debug] PHP Notice: in file [ROOT]/ext/wardormeur/phpbbwpunicorn/user.php on line 136: Undefined index: user_yim
[phpBB Debug] PHP Notice: in file [ROOT]/ext/wardormeur/phpbbwpunicorn/user.php on line 131: Undefined index: user_website
[phpBB Debug] PHP Notice: in file [ROOT]/ext/wardormeur/phpbbwpunicorn/user.php on line 135: Undefined index: user_aim
[phpBB Debug] PHP Notice: in file [ROOT]/ext/wardormeur/phpbbwpunicorn/user.php on line 136: Undefined index: user_yim
[phpBB Debug] PHP Notice: in file [ROOT]/ext/wardormeur/phpbbwpunicorn/user.php on line 131: Undefined index: user_website
[phpBB Debug] PHP Notice: in file [ROOT]/ext/wardormeur/phpbbwpunicorn/user.php on line 135: Undefined index: user_aim
[phpBB Debug] PHP Notice: in file [ROOT]/ext/wardormeur/phpbbwpunicorn/user.php on line 136: Undefined index: user_yim
[phpBB Debug] PHP Notice: in file [ROOT]/ext/wardormeur/phpbbwpunicorn/user.php on line 131: Undefined index: user_website
[phpBB Debug] PHP Notice: in file [ROOT]/ext/wardormeur/phpbbwpunicorn/user.php on line 135: Undefined index: user_aim
[phpBB Debug] PHP Notice: in file [ROOT]/ext/wardormeur/phpbbwpunicorn/user.php on line 136: Undefined index: user_yim
[phpBB Debug] PHP Notice: in file [ROOT]/ext/wardormeur/phpbbwpunicorn/user.php on line 131: Undefined index: user_website
[phpBB Debug] PHP Notice: in file [ROOT]/ext/wardormeur/phpbbwpunicorn/user.php on line 135: Undefined index: user_aim
[phpBB Debug] PHP Notice: in file [ROOT]/ext/wardormeur/phpbbwpunicorn/user.php on line 136: Undefined index: user_yim
[phpBB Debug] PHP Notice: in file [ROOT]/ext/wardormeur/phpbbwpunicorn/user.php on line 131: Undefined index: user_website
[phpBB Debug] PHP Notice: in file [ROOT]/ext/wardormeur/phpbbwpunicorn/user.php on line 135: Undefined index: user_aim
[phpBB Debug] PHP Notice: in file [ROOT]/ext/wardormeur/phpbbwpunicorn/user.php on line 136: Undefined index: user_yim
[phpBB Debug] PHP Notice: in file [ROOT]/ext/wardormeur/phpbbwpunicorn/user.php on line 131: Undefined index: user_website
[phpBB Debug] PHP Notice: in file [ROOT]/ext/wardormeur/phpbbwpunicorn/user.php on line 135: Undefined index: user_aim
[phpBB Debug] PHP Notice: in file [ROOT]/ext/wardormeur/phpbbwpunicorn/user.php on line 136: Undefined index: user_yim
[phpBB Debug] PHP Notice: in file [ROOT]/ext/wardormeur/phpbbwpunicorn/user.php on line 131: Undefined index: user_website
[phpBB Debug] PHP Notice: in file [ROOT]/ext/wardormeur/phpbbwpunicorn/user.php on line 135: Undefined index: user_aim
[phpBB Debug] PHP Notice: in file [ROOT]/ext/wardormeur/phpbbwpunicorn/user.php on line 136: Undefined index: user_yim
[phpBB Debug] PHP Notice: in file [ROOT]/ext/wardormeur/phpbbwpunicorn/user.php on line 131: Undefined index: user_website
[phpBB Debug] PHP Notice: in file [ROOT]/ext/wardormeur/phpbbwpunicorn/user.php on line 135: Undefined index: user_aim
[phpBB Debug] PHP Notice: in file [ROOT]/ext/wardormeur/phpbbwpunicorn/user.php on line 136: Undefined index: user_yim
[phpBB Debug] PHP Notice: in file [ROOT]/ext/wardormeur/phpbbwpunicorn/user.php on line 131: Undefined index: user_website
[phpBB Debug] PHP Notice: in file [ROOT]/ext/wardormeur/phpbbwpunicorn/user.php on line 135: Undefined index: user_aim
[phpBB Debug] PHP Notice: in file [ROOT]/ext/wardormeur/phpbbwpunicorn/user.php on line 136: Undefined index: user_yim
[phpBB Debug] PHP Notice: in file [ROOT]/ext/wardormeur/phpbbwpunicorn/user.php on line 131: Undefined index: user_website
[phpBB Debug] PHP Notice: in file [ROOT]/ext/wardormeur/phpbbwpunicorn/user.php on line 135: Undefined index: user_aim
[phpBB Debug] PHP Notice: in file [ROOT]/ext/wardormeur/phpbbwpunicorn/user.php on line 136: Undefined index: user_yim
[phpBB Debug] PHP Notice: in file [ROOT]/ext/wardormeur/phpbbwpunicorn/user.php on line 131: Undefined index: user_website
[phpBB Debug] PHP Notice: in file [ROOT]/ext/wardormeur/phpbbwpunicorn/user.php on line 135: Undefined index: user_aim
[phpBB Debug] PHP Notice: in file [ROOT]/ext/wardormeur/phpbbwpunicorn/user.php on line 136: Undefined index: user_yim
[phpBB Debug] PHP Notice: in file [ROOT]/ext/wardormeur/phpbbwpunicorn/user.php on line 131: Undefined index: user_website
[phpBB Debug] PHP Notice: in file [ROOT]/ext/wardormeur/phpbbwpunicorn/user.php on line 135: Undefined index: user_aim
[phpBB Debug] PHP Notice: in file [ROOT]/ext/wardormeur/phpbbwpunicorn/user.php on line 136: Undefined index: user_yim
[phpBB Debug] PHP Notice: in file [ROOT]/ext/wardormeur/phpbbwpunicorn/user.php on line 131: Undefined index: user_website
[phpBB Debug] PHP Notice: in file [ROOT]/ext/wardormeur/phpbbwpunicorn/user.php on line 135: Undefined index: user_aim
[phpBB Debug] PHP Notice: in file [ROOT]/ext/wardormeur/phpbbwpunicorn/user.php on line 136: Undefined index: user_yim
[phpBB Debug] PHP Notice: in file [ROOT]/ext/wardormeur/phpbbwpunicorn/user.php on line 131: Undefined index: user_website
[phpBB Debug] PHP Notice: in file [ROOT]/ext/wardormeur/phpbbwpunicorn/user.php on line 135: Undefined index: user_aim
[phpBB Debug] PHP Notice: in file [ROOT]/ext/wardormeur/phpbbwpunicorn/user.php on line 136: Undefined index: user_yim
[phpBB Debug] PHP Notice: in file [ROOT]/ext/wardormeur/phpbbwpunicorn/user.php on line 131: Undefined index: user_website
[phpBB Debug] PHP Notice: in file [ROOT]/ext/wardormeur/phpbbwpunicorn/user.php on line 135: Undefined index: user_aim
[phpBB Debug] PHP Notice: in file [ROOT]/ext/wardormeur/phpbbwpunicorn/user.php on line 136: Undefined index: user_yim
[phpBB Debug] PHP Notice: in file [ROOT]/ext/wardormeur/phpbbwpunicorn/user.php on line 131: Undefined index: user_website
[phpBB Debug] PHP Notice: in file [ROOT]/ext/wardormeur/phpbbwpunicorn/user.php on line 135: Undefined index: user_aim
[phpBB Debug] PHP Notice: in file [ROOT]/ext/wardormeur/phpbbwpunicorn/user.php on line 136: Undefined index: user_yim
[phpBB Debug] PHP Notice: in file [ROOT]/ext/wardormeur/phpbbwpunicorn/user.php on line 131: Undefined index: user_website
[phpBB Debug] PHP Notice: in file [ROOT]/ext/wardormeur/phpbbwpunicorn/user.php on line 135: Undefined index: user_aim
[phpBB Debug] PHP Notice: in file [ROOT]/ext/wardormeur/phpbbwpunicorn/user.php on line 136: Undefined index: user_yim
[phpBB Debug] PHP Notice: in file [ROOT]/ext/wardormeur/phpbbwpunicorn/user.php on line 131: Undefined index: user_website
[phpBB Debug] PHP Notice: in file [ROOT]/ext/wardormeur/phpbbwpunicorn/user.php on line 135: Undefined index: user_aim
[phpBB Debug] PHP Notice: in file [ROOT]/ext/wardormeur/phpbbwpunicorn/user.php on line 136: Undefined index: user_yim
[phpBB Debug] PHP Notice: in file [ROOT]/ext/wardormeur/phpbbwpunicorn/user.php on line 131: Undefined index: user_website
[phpBB Debug] PHP Notice: in file [ROOT]/ext/wardormeur/phpbbwpunicorn/user.php on line 135: Undefined index: user_aim
[phpBB Debug] PHP Notice: in file [ROOT]/ext/wardormeur/phpbbwpunicorn/user.php on line 136: Undefined index: user_yim
[phpBB Debug] PHP Notice: in file [ROOT]/ext/wardormeur/phpbbwpunicorn/user.php on line 131: Undefined index: user_website
[phpBB Debug] PHP Notice: in file [ROOT]/ext/wardormeur/phpbbwpunicorn/user.php on line 135: Undefined index: user_aim
[phpBB Debug] PHP Notice: in file [ROOT]/ext/wardormeur/phpbbwpunicorn/user.php on line 136: Undefined index: user_yim
[phpBB Debug] PHP Notice: in file [ROOT]/ext/wardormeur/phpbbwpunicorn/user.php on line 131: Undefined index: user_website
[phpBB Debug] PHP Notice: in file [ROOT]/ext/wardormeur/phpbbwpunicorn/user.php on line 135: Undefined index: user_aim
[phpBB Debug] PHP Notice: in file [ROOT]/ext/wardormeur/phpbbwpunicorn/user.php on line 136: Undefined index: user_yim
[phpBB Debug] PHP Notice: in file [ROOT]/ext/wardormeur/phpbbwpunicorn/user.php on line 131: Undefined index: user_website
[phpBB Debug] PHP Notice: in file [ROOT]/ext/wardormeur/phpbbwpunicorn/user.php on line 135: Undefined index: user_aim
[phpBB Debug] PHP Notice: in file [ROOT]/ext/wardormeur/phpbbwpunicorn/user.php on line 136: Undefined index: user_yim
[phpBB Debug] PHP Notice: in file [ROOT]/ext/wardormeur/phpbbwpunicorn/user.php on line 131: Undefined index: user_website
[phpBB Debug] PHP Notice: in file [ROOT]/ext/wardormeur/phpbbwpunicorn/user.php on line 135: Undefined index: user_aim
[phpBB Debug] PHP Notice: in file [ROOT]/ext/wardormeur/phpbbwpunicorn/user.php on line 136: Undefined index: user_yim
[phpBB Debug] PHP Notice: in file [ROOT]/ext/wardormeur/phpbbwpunicorn/user.php on line 131: Undefined index: user_website
[phpBB Debug] PHP Notice: in file [ROOT]/ext/wardormeur/phpbbwpunicorn/user.php on line 135: Undefined index: user_aim
[phpBB Debug] PHP Notice: in file [ROOT]/ext/wardormeur/phpbbwpunicorn/user.php on line 136: Undefined index: user_yim
[phpBB Debug] PHP Notice: in file [ROOT]/ext/wardormeur/phpbbwpunicorn/user.php on line 131: Undefined index: user_website
[phpBB Debug] PHP Notice: in file [ROOT]/ext/wardormeur/phpbbwpunicorn/user.php on line 135: Undefined index: user_aim
[phpBB Debug] PHP Notice: in file [ROOT]/ext/wardormeur/phpbbwpunicorn/user.php on line 136: Undefined index: user_yim
[phpBB Debug] PHP Notice: in file [ROOT]/ext/wardormeur/phpbbwpunicorn/user.php on line 131: Undefined index: user_website
[phpBB Debug] PHP Notice: in file [ROOT]/ext/wardormeur/phpbbwpunicorn/user.php on line 135: Undefined index: user_aim
[phpBB Debug] PHP Notice: in file [ROOT]/ext/wardormeur/phpbbwpunicorn/user.php on line 136: Undefined index: user_yim
[phpBB Debug] PHP Notice: in file [ROOT]/ext/wardormeur/phpbbwpunicorn/user.php on line 131: Undefined index: user_website
[phpBB Debug] PHP Notice: in file [ROOT]/ext/wardormeur/phpbbwpunicorn/user.php on line 135: Undefined index: user_aim
[phpBB Debug] PHP Notice: in file [ROOT]/ext/wardormeur/phpbbwpunicorn/user.php on line 136: Undefined index: user_yim
[phpBB Debug] PHP Notice: in file [ROOT]/ext/wardormeur/phpbbwpunicorn/user.php on line 131: Undefined index: user_website
[phpBB Debug] PHP Notice: in file [ROOT]/ext/wardormeur/phpbbwpunicorn/user.php on line 135: Undefined index: user_aim
[phpBB Debug] PHP Notice: in file [ROOT]/ext/wardormeur/phpbbwpunicorn/user.php on line 136: Undefined index: user_yim
[phpBB Debug] PHP Notice: in file [ROOT]/ext/wardormeur/phpbbwpunicorn/user.php on line 131: Undefined index: user_website
[phpBB Debug] PHP Notice: in file [ROOT]/ext/wardormeur/phpbbwpunicorn/user.php on line 135: Undefined index: user_aim
[phpBB Debug] PHP Notice: in file [ROOT]/ext/wardormeur/phpbbwpunicorn/user.php on line 136: Undefined index: user_yim
[phpBB Debug] PHP Notice: in file [ROOT]/ext/wardormeur/phpbbwpunicorn/user.php on line 131: Undefined index: user_website
[phpBB Debug] PHP Notice: in file [ROOT]/ext/wardormeur/phpbbwpunicorn/user.php on line 135: Undefined index: user_aim
[phpBB Debug] PHP Notice: in file [ROOT]/ext/wardormeur/phpbbwpunicorn/user.php on line 136: Undefined index: user_yim
[phpBB Debug] PHP Notice: in file [ROOT]/ext/wardormeur/phpbbwpunicorn/user.php on line 131: Undefined index: user_website
[phpBB Debug] PHP Notice: in file [ROOT]/ext/wardormeur/phpbbwpunicorn/user.php on line 135: Undefined index: user_aim
[phpBB Debug] PHP Notice: in file [ROOT]/ext/wardormeur/phpbbwpunicorn/user.php on line 136: Undefined index: user_yim
[phpBB Debug] PHP Notice: in file [ROOT]/ext/wardormeur/phpbbwpunicorn/user.php on line 131: Undefined index: user_website
[phpBB Debug] PHP Notice: in file [ROOT]/ext/wardormeur/phpbbwpunicorn/user.php on line 135: Undefined index: user_aim
[phpBB Debug] PHP Notice: in file [ROOT]/ext/wardormeur/phpbbwpunicorn/user.php on line 136: Undefined index: user_yim
[phpBB Debug] PHP Notice: in file [ROOT]/ext/wardormeur/phpbbwpunicorn/user.php on line 131: Undefined index: user_website
[phpBB Debug] PHP Notice: in file [ROOT]/ext/wardormeur/phpbbwpunicorn/user.php on line 135: Undefined index: user_aim
[phpBB Debug] PHP Notice: in file [ROOT]/ext/wardormeur/phpbbwpunicorn/user.php on line 136: Undefined index: user_yim
[phpBB Debug] PHP Notice: in file [ROOT]/ext/wardormeur/phpbbwpunicorn/user.php on line 131: Undefined index: user_website
[phpBB Debug] PHP Notice: in file [ROOT]/ext/wardormeur/phpbbwpunicorn/user.php on line 135: Undefined index: user_aim
[phpBB Debug] PHP Notice: in file [ROOT]/ext/wardormeur/phpbbwpunicorn/user.php on line 136: Undefined index: user_yim
[phpBB Debug] PHP Notice: in file [ROOT]/ext/wardormeur/phpbbwpunicorn/user.php on line 131: Undefined index: user_website
[phpBB Debug] PHP Notice: in file [ROOT]/ext/wardormeur/phpbbwpunicorn/user.php on line 135: Undefined index: user_aim
[phpBB Debug] PHP Notice: in file [ROOT]/ext/wardormeur/phpbbwpunicorn/user.php on line 136: Undefined index: user_yim
[phpBB Debug] PHP Notice: in file [ROOT]/ext/wardormeur/phpbbwpunicorn/user.php on line 131: Undefined index: user_website
[phpBB Debug] PHP Notice: in file [ROOT]/ext/wardormeur/phpbbwpunicorn/user.php on line 135: Undefined index: user_aim
[phpBB Debug] PHP Notice: in file [ROOT]/ext/wardormeur/phpbbwpunicorn/user.php on line 136: Undefined index: user_yim
[phpBB Debug] PHP Notice: in file [ROOT]/ext/wardormeur/phpbbwpunicorn/user.php on line 131: Undefined index: user_website
[phpBB Debug] PHP Notice: in file [ROOT]/ext/wardormeur/phpbbwpunicorn/user.php on line 135: Undefined index: user_aim
[phpBB Debug] PHP Notice: in file [ROOT]/ext/wardormeur/phpbbwpunicorn/user.php on line 136: Undefined index: user_yim
[phpBB Debug] PHP Notice: in file [ROOT]/ext/wardormeur/phpbbwpunicorn/user.php on line 131: Undefined index: user_website
[phpBB Debug] PHP Notice: in file [ROOT]/ext/wardormeur/phpbbwpunicorn/user.php on line 135: Undefined index: user_aim
[phpBB Debug] PHP Notice: in file [ROOT]/ext/wardormeur/phpbbwpunicorn/user.php on line 136: Undefined index: user_yim
[phpBB Debug] PHP Notice: in file [ROOT]/ext/wardormeur/phpbbwpunicorn/user.php on line 131: Undefined index: user_website
[phpBB Debug] PHP Notice: in file [ROOT]/ext/wardormeur/phpbbwpunicorn/user.php on line 135: Undefined index: user_aim
[phpBB Debug] PHP Notice: in file [ROOT]/ext/wardormeur/phpbbwpunicorn/user.php on line 136: Undefined index: user_yim
[phpBB Debug] PHP Notice: in file [ROOT]/ext/wardormeur/phpbbwpunicorn/user.php on line 131: Undefined index: user_website
[phpBB Debug] PHP Notice: in file [ROOT]/ext/wardormeur/phpbbwpunicorn/user.php on line 135: Undefined index: user_aim
[phpBB Debug] PHP Notice: in file [ROOT]/ext/wardormeur/phpbbwpunicorn/user.php on line 136: Undefined index: user_yim
[phpBB Debug] PHP Notice: in file [ROOT]/ext/wardormeur/phpbbwpunicorn/user.php on line 131: Undefined index: user_website
[phpBB Debug] PHP Notice: in file [ROOT]/ext/wardormeur/phpbbwpunicorn/user.php on line 135: Undefined index: user_aim
[phpBB Debug] PHP Notice: in file [ROOT]/ext/wardormeur/phpbbwpunicorn/user.php on line 136: Undefined index: user_yim
[phpBB Debug] PHP Notice: in file [ROOT]/ext/wardormeur/phpbbwpunicorn/user.php on line 131: Undefined index: user_website
[phpBB Debug] PHP Notice: in file [ROOT]/ext/wardormeur/phpbbwpunicorn/user.php on line 135: Undefined index: user_aim
[phpBB Debug] PHP Notice: in file [ROOT]/ext/wardormeur/phpbbwpunicorn/user.php on line 136: Undefined index: user_yim
[phpBB Debug] PHP Notice: in file [ROOT]/ext/wardormeur/phpbbwpunicorn/user.php on line 131: Undefined index: user_website
[phpBB Debug] PHP Notice: in file [ROOT]/ext/wardormeur/phpbbwpunicorn/user.php on line 135: Undefined index: user_aim
[phpBB Debug] PHP Notice: in file [ROOT]/ext/wardormeur/phpbbwpunicorn/user.php on line 136: Undefined index: user_yim
[phpBB Debug] PHP Notice: in file [ROOT]/ext/wardormeur/phpbbwpunicorn/user.php on line 131: Undefined index: user_website
[phpBB Debug] PHP Notice: in file [ROOT]/ext/wardormeur/phpbbwpunicorn/user.php on line 135: Undefined index: user_aim
[phpBB Debug] PHP Notice: in file [ROOT]/ext/wardormeur/phpbbwpunicorn/user.php on line 136: Undefined index: user_yim
[phpBB Debug] PHP Notice: in file [ROOT]/ext/wardormeur/phpbbwpunicorn/user.php on line 131: Undefined index: user_website
[phpBB Debug] PHP Notice: in file [ROOT]/ext/wardormeur/phpbbwpunicorn/user.php on line 135: Undefined index: user_aim
[phpBB Debug] PHP Notice: in file [ROOT]/ext/wardormeur/phpbbwpunicorn/user.php on line 136: Undefined index: user_yim
[phpBB Debug] PHP Notice: in file [ROOT]/ext/wardormeur/phpbbwpunicorn/user.php on line 131: Undefined index: user_website
[phpBB Debug] PHP Notice: in file [ROOT]/ext/wardormeur/phpbbwpunicorn/user.php on line 135: Undefined index: user_aim
[phpBB Debug] PHP Notice: in file [ROOT]/ext/wardormeur/phpbbwpunicorn/user.php on line 136: Undefined index: user_yim
[phpBB Debug] PHP Notice: in file [ROOT]/ext/wardormeur/phpbbwpunicorn/user.php on line 131: Undefined index: user_website
[phpBB Debug] PHP Notice: in file [ROOT]/ext/wardormeur/phpbbwpunicorn/user.php on line 135: Undefined index: user_aim
[phpBB Debug] PHP Notice: in file [ROOT]/ext/wardormeur/phpbbwpunicorn/user.php on line 136: Undefined index: user_yim
[phpBB Debug] PHP Notice: in file [ROOT]/ext/wardormeur/phpbbwpunicorn/user.php on line 131: Undefined index: user_website
[phpBB Debug] PHP Notice: in file [ROOT]/ext/wardormeur/phpbbwpunicorn/user.php on line 135: Undefined index: user_aim
[phpBB Debug] PHP Notice: in file [ROOT]/ext/wardormeur/phpbbwpunicorn/user.php on line 136: Undefined index: user_yim

Warning: Cannot modify header information - headers already sent by (output started at /forum/includes/functions.php:3903) in /forum/includes/functions_acp.php on line 132

Warning: Cannot modify header information - headers already sent by (output started at /forum/includes/functions.php:3903) in /forum/includes/functions_acp.php on line 132

Warning: Cannot modify header information - headers already sent by (output started at /forum/includes/functions.php:3903) in /forum/includes/functions_acp.php on line 132

**Comment by Wardormeur** [comment]
Yeah, most of those reference to user-pref have been removed in latest version of phpbb, need to keep up to date :)

**Comment by RARgames** [comment]
Yeah, I didn't clear cache again, sorry
